version: '3.1'

services:
  comedor_pg:
    image: postgres:15.1
    container_name: comedor_pg
    environment:
      POSTGRES_DB: comedor
      POSTGRES_USER: ucomedor
      POSTGRES_PASSWORD: secret123456
    ports:
      - 5432:5432
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql